In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
df = pd.read_csv('https://www.ispdados.rj.gov.br/Arquivos/BaseMunicipioMensal.csv', sep = ';',  encoding= 'latin1')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12604 entries, 0 to 12603
Data columns (total 60 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   fmun_cod                    12604 non-null  int64
 1   fmun                        12604 non-null  object
 2   ano                         12604 non-null  int64
 3   mes                         12604 non-null  int64
 4   mes_ano                     12604 non-null  object
 5   regiao                      12604 non-null  object
 6   hom_doloso                  12604 non-null  int64
 7   lesao_corp_morte            12604 non-null  int64
 8   latrocinio                  12604 non-null  int64
 9   cvli                        12604 non-null  int64
 10  hom_por_interv_policial     12604 non-null  int64
 11  letalidade_violenta         12604 non-null  int64
 12  tentat_hom                  12604 non-null  int64
 13  lesao_corp_dolosa           12604 non-null  int64
 14  estupro                     12604 non-null  int64
 15  hom_culposo                 12604 non-null  int64
 16  lesao_corp_culposa          12604 non-null  int64
 17  roubo_transeunte            12604 non-null  int64
 18  roubo_celular               12604 non-null  int64
 19  roubo_em_coletivo           12604 non-null  int64
 20  roubo_rua                   12604 non-null  int64
 21  roubo_veiculo               12604 non-null  int64
 22  roubo_carga                 12604 non-null  int64
 23  roubo_comercio              12604 non-null  int64
 24  roubo_residencia            12604 non-null  int64
 25  roubo_banco                 12604 non-null  int64
 26  roubo_cx_eletronico         12604 non-null  int64
 27  roubo_conducao_saque        12604 non-null  int64
 28  roubo_apos_saque            12604 non-null  int64
 29  roubo_bicicleta             12604 non-null  int64
 30  outros_roubos               12604 non-null  int64
 31  total_roubos                12604 non-null  int64
 32  furto_veiculos              12604 non-null  int64
 33  furto_transeunte            12604 non-null  int64
 34  furto_coletivo              12604 non-null  int64
 35  furto_celular               12604 non-null  int64
 36  furto_bicicleta             12604 non-null  int64
 37  outros_furtos               12604 non-null  int64
 38  total_furtos                12604 non-null  int64
 39  sequestro                   12604 non-null  int64
 40  extorsao                    12604 non-null  int64
 41  sequestro_relampago         12604 non-null  int64
 42  estelionato                 12604 non-null  int64
 43  apreensao_drogas            12604 non-null  int64
 44  posse_drogas                12604 non-null  int64
 45  trafico_drogas              12604 non-null  int64
 46  apreensao_drogas_sem_autor  12604 non-null  int64
 47  recuperacao_veiculos        12604 non-null  int64
 48  apf                         12604 non-null  int64
 49  aaapai                      12604 non-null  int64
 50  cmp                         12604 non-null  int64
 51  cmba                        12604 non-null  int64
 52  ameaca                      12604 non-null  int64
 53  pessoas_desaparecidas       12604 non-null  int64
 54  encontro_cadaver            12604 non-null  int64
 55  encontro_ossada             12604 non-null  int64
 56  pol_militares_mortos_serv   12604 non-null  int64
 57  pol_civis_mortos_serv       12604 non-null  int64
 58  registro_ocorrencias        12604 non-null  int64
 59  fase                        12604 non-null  int64
dtypes: int64(57), object(3)
memory usage: 5.8+ MB

In [9]:
df

,fmun_cod,fmun,ano,mes,mes_ano,regiao,hom_doloso,lesao_corp_morte,latrocinio,cvli,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,3300100,Angra dos Reis,2014,1,2014m01,Interior,11,0,0,11,...,8,0,98,13,3,0,0,0,561,3
1,3300159,AperibÃ©,2014,1,2014m01,Interior,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
2,3300209,Araruama,2014,1,2014m01,Interior,2,0,0,2,...,5,0,91,10,1,0,0,0,480,3
3,3300225,Areal,2014,1,2014m01,Interior,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
4,3300233,ArmaÃ§Ã£o dos BÃºzios,2014,1,2014m01,Interior,2,0,0,2,...,3,2,46,0,0,0,0,0,309,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12599,3306008,TrÃªs Rios,2025,5,2025m05,Interior,5,0,0,5,...,15,0,60,1,0,0,0,0,493,2
12600,3306107,ValenÃ§a,2025,5,2025m05,Interior,4,0,0,4,...,9,0,32,1,0,0,0,0,257,2
12601,3306156,Varre-Sai,2025,5,2025m05,Interior,0,0,0,0,...,0,0,8,0,0,0,0,0,23,2
12602,3306206,Vassouras,2025,5,2025m05,Interior,0,0,0,0,...,3,0,17,1,0,0,0,0,131,2
12603,3306305,Volta Redonda,2025,5,2025m05,Interior,5,0,0,5,...,15,0,185,14,0,0,0,0,1519,2

In [13]:
df_menor = df.groupby(['regiao', 'fmun'])['aaapai'].sum().reset_index()
df_menor = df.loc('regiao'== 'Baixada Fluminense')
df_menor